"""
Ingredient tagging for recipes.

The spreadsheet has no ingredient column, so tags are derived by matching
the recipe name + instructions against this dictionary. Each entry is
(tag, regex). Regexes are matched case-insensitively. Edit freely; the
server re-tags on every fetch, so no restart is needed beyond a refresh.
"""

import re

INGREDIENTS = [
    # Proteins
    ("chicken", r"chicken(?!\s+(?:stock|broth|bone broth|bouillon|sausage))"),
    ("chicken sausage", r"chicken sausage"),
    ("chicken thighs", r"chicken thigh"),
    ("ground beef", r"ground (?:beef|veal)|keema"),
    ("beef", r"\bbeef\b|stew meat|\bsteaks?\b|\bveal\b|carne asada|bulgogi"),
    ("turkey", r"\bturkey\b(?!\s+bacon)"),
    ("shrimp", r"shrimp"),
    ("salmon", r"salmon"),
    ("mahi mahi", r"mahi"),
    ("smoked trout", r"trout"),
    ("mussels", r"mussels"),
    ("mackerel", r"mackerel"),
    ("fish", r"\bfish\b(?!\s+sauce)|mahi|salmon|trout|mackerel|tinned fish"),
    ("seafood", r"seafood"),
    ("tofu", r"tofu"),
    ("soy chorizo", r"soy chorizo"),
    ("eggs", r"\beggs?\b(?!\s+(?:noodles|wash))"),
    # Legumes & grains
    ("chickpeas", r"chickpea|channa|chana"),
    ("lentils", r"lentil|\bdaal\b|\bdal\b"),
    ("white beans", r"white beans?"),
    ("edamame", r"edamame"),
    ("farro", r"farro"),
    ("rice", r"\brice\b(?!\s+(?:vinegar|paper|noodles|syrup|flour))"),
    ("rice noodles", r"rice noodles"),
    ("noodles", r"noodles|ramen|pad thai"),
    ("pasta", r"\bpasta\b|papardelle|pappardelle|gnocchi|\borzo\b|lasagna|spaghetti|penne"),
    ("gnocchi", r"gnocchi"),
    ("oats", r"\boats?\b|oat flour"),
    ("flour", r"\bflour\b"),
    ("bread", r"\bbread\b|baguette|sourdough|\bnaan\b|\bpita\b|lavash|tortilla|bagel|\bbuns?\b"),
    ("panko / breadcrumbs", r"panko|breadcrumb"),
    # Vegetables
    ("potato", r"(?<!sweet )(?<!sweet  )potato(?:es)?\b|\btaters\b"),
    ("sweet potato", r"sweet potato"),
    ("spinach", r"spinach"),
    ("kale", r"\bkale\b"),
    ("bok choy", r"bok choy"),
    ("broccoli", r"broccoli"),
    ("cauliflower", r"cauliflower"),
    ("brussels sprouts", r"brussels"),
    ("zucchini", r"zucchini"),
    ("asparagus", r"asparagus"),
    ("peas", r"\bpeas\b"),
    ("corn", r"\bcorn\b(?!\s*starch)"),
    ("carrot", r"carrot"),
    ("bell pepper", r"bell pepper"),
    ("cucumber", r"cucumber"),
    ("radish", r"radish"),
    ("arugula", r"arugula"),
    ("cabbage", r"cabbage|\bslaw\b"),
    ("lettuce", r"lettuce"),
    ("mushrooms", r"mushroom"),
    ("tomato", r"tomato(?:es)?\b(?!\s+paste)"),
    ("tomato paste", r"tomato paste"),
    ("onion", r"(?<!green )(?<!fried )onions?\b"),
    ("green onion", r"green onion|scallion"),
    ("shallot", r"shallot"),
    ("garlic", r"garlic(?!\s+powder)"),
    ("ginger", r"ginger"),
    ("chilies", r"jalape|green chil|serrano|thai red chil|hatch chil|red chil(?:i|e)s\b|chile"),
    ("calabrian chili", r"calabrian"),
    ("squash", r"squash"),
    # Fruit
    ("lemon", r"lemon"),
    ("lime", r"\blime"),
    ("orange", r"\boranges?\b(?!\s+food)"),
    ("peach", r"peach"),
    ("banana", r"banana"),
    ("dates", r"\bdates\b"),
    ("plum", r"\bplums?\b"),
    ("mango", r"mango"),
    ("pear", r"\bpear\b"),
    ("gooseberries", r"gooseberr"),
    # Dairy & fats
    ("yogurt", r"yogurt|labneh"),
    ("cheese", r"cheese|mozzarella|cheddar|\bparm|feta|pepper jack|burrata"),
    ("feta", r"feta"),
    ("parmesan", r"\bparm"),
    ("mozzarella", r"mozzarella"),
    ("heavy cream", r"heavy cream"),
    ("coconut milk", r"coconut (?:milk|cream)"),
    ("butter", r"(?<!peanut )(?<!miso )butter\b(?!\s+lettuce)"),
    ("ghee", r"\bghee\b"),
    ("milk", r"(?<!coconut )(?<!almond )(?<!oat )\bmilk\b"),
    # Sauces, pastes, condiments
    ("miso", r"\bmiso\b"),
    ("tahini", r"tahini"),
    ("peanut butter", r"peanut butter|\bpb\b"),
    ("peanuts", r"peanuts"),
    ("sesame", r"sesame"),
    ("soy sauce", r"soy sauce"),
    ("fish sauce", r"fish sauce"),
    ("gochujang", r"gochujang|gojuchang"),
    ("curry paste", r"curry paste"),
    ("curry powder", r"curry powder"),
    ("pesto", r"pesto"),
    ("nutritional yeast", r"nutritional yeast"),
    ("mayo", r"\bmayo"),
    ("hot sauce", r"hot sauce|sriracha|sambal|chili crunch|chili oil"),
    ("honey", r"honey"),
    ("maple syrup", r"maple"),
    ("chocolate chips", r"choc(?:olate)? chips"),
    ("stock / broth", r"\bstock\b|broth|bouillon"),
    # Herbs & spices
    ("cilantro", r"cilantro"),
    ("dill", r"\bdill\b"),
    ("mint", r"\bmint\b"),
    ("basil", r"basil"),
    ("parsley", r"parsley"),
    ("thyme", r"thyme"),
    ("oregano", r"oregano"),
    ("zaatar", r"za+tar"),
    ("saffron", r"saffron"),
    ("cinnamon", r"cinnamon"),
    ("cardamom", r"cardamom"),
    ("cumin", r"cumin"),
    ("coriander", r"coriander"),
    ("turmeric", r"turmeric|tumeric|haldi"),
    ("garam masala", r"garam masala"),
    ("paprika", r"paprika"),
    ("cayenne", r"cayenne"),
    ("chili flakes", r"chil[ie] flakes|red pepper flakes|red pep\b"),
    ("mustard seeds", r"mustard seed"),
    ("bay leaf", r"bay lea"),
]

_COMPILED = [(tag, re.compile(pat, re.IGNORECASE)) for tag, pat in INGREDIENTS]


def tag_text(text):
    """Return the list of ingredient tags found in `text`, in dictionary order."""
    return [tag for tag, rx in _COMPILED if rx.search(text)]
